language: java
jdk: oraclejdk8

install: true

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - git@gsc-dev.net
    on_success: never # default: change
    on_failure: always # default: always

script:
  - bash <(curl -s https://codecov.io/bash)